name: holographic-parallax
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0
  - appdirs=1.4.4
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - configargparse=1.5.3
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cccl=12.1.55
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - eigen=3.4.0
  - ffmpeg=4.2.3
  - fftw=3.3.9
  - filelock=3.9.0
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2022.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imageio=2.27.0
  - importlib-metadata=6.1.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.2
  - libiconv=1.17
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libogg=1.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.3
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.6.0
  - openssl=1.1.1w
  - packaging=23.0
  - partd=1.2.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pooch=1.4.0
  - protobuf=3.20.3
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - scikit-image=0.19.3
  - scipy=1.10.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.1
  - sympy=1.11.1
  - tensorboard=1.15.0
  - tifffile=2020.10.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - typing_extensions=4.4.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.3
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - torchvision==0.15.0
